# Generated by Django 6.0.1 on 2026-03-15 03:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0004_delivery_zone_store_coords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('config', models.JSONField(default=dict, verbose_name='Конфигурация виджетов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Дашборд',
                'verbose_name_plural': 'Дашборды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('sales', 'Продажи'), ('products', 'Товары'), ('orders', 'Заказы'), ('revenue', 'Выручка')], max_length=20, verbose_name='Тип отчёта')),
                ('date_from', models.DateField(verbose_name='Дата начала')),
                ('date_to', models.DateField(verbose_name='Дата окончания')),
                ('data', models.JSONField(default=dict, verbose_name='Данные')),
                ('format', models.CharField(choices=[('json', 'JSON'), ('excel', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF')], default='json', max_length=10, verbose_name='Формат')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='stores.store', verbose_name='Точка продаж')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('revenue', 'Выручка'), ('orders_count', 'Количество заказов'), ('avg_order_value', 'Средний чек'), ('products_sold', 'Продано товаров')], max_length=30, verbose_name='Тип метрики')),
                ('date', models.DateField(verbose_name='Дата')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Значение')),
                ('metadata', models.JSONField(default=dict, verbose_name='Метаданные')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='stores.store', verbose_name='Точка продаж')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('store__isnull', False)), fields=('metric_type', 'store', 'date'), name='unique_metric_store_date'), models.UniqueConstraint(condition=models.Q(('store__isnull', True)), fields=('metric_type', 'date'), name='unique_metric_no_store_date')],
            },
        ),
    ]
