# Generated by Django 6.0.1 on 2026-01-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Город"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Улица"
                    ),
                ),
                ("house", models.CharField(max_length=50, verbose_name="Дом")),
                (
                    "apartment",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Квартира/Офис",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Координата для расчета расстояний",
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Координата для расчета расстояний",
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
                "indexes": [
                    models.Index(
                        fields=["city", "street"], name="common_addr_city_31b1b5_idx"
                    )
                ],
            },
        ),
    ]
