# Generated by Django 6.0.1 on 2026-02-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Дополнительная информация к адресу",
                null=True,
                verbose_name="Комментарий",
            ),
        ),
    ]
