# Generated by Django 6.0.1 on 2026-03-15 03:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_add_package_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnReason',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Причина возврата',
                'verbose_name_plural': 'Причины возврата',
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В обработке'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма возврата')),
                ('refund_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], max_length=10, verbose_name='Способ возврата')),
                ('refund_status', models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Выполнен'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус возврата средств')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён в')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.order', verbose_name='Заказ')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='returns.returnreason', verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма возврата')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.orderitem', verbose_name='Позиция заказа')),
                ('return_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.return', verbose_name='Возврат')),
            ],
            options={
                'verbose_name': 'Позиция возврата',
                'verbose_name_plural': 'Позиции возврата',
            },
        ),
        migrations.CreateModel(
            name='ReturnStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменён в')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('return_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='returns.return', verbose_name='Возврат')),
            ],
            options={
                'verbose_name': 'История статусов возврата',
                'verbose_name_plural': 'История статусов возвратов',
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['order'], name='returns_ret_order_i_45751c_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['order', 'created_at'], name='returns_ret_order_i_670939_idx'),
        ),
    ]
