# Generated by Django 6.0.1 on 2026-01-26 08:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Удалено"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_order_push_notifications_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Push уведомления о заказах"
                    ),
                ),
                (
                    "is_promo_push_notifications_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Push уведомления о скидках"
                    ),
                ),
                (
                    "is_promo_sms_notifications_enabled",
                    models.BooleanField(
                        default=True, verbose_name="SMS уведомления о скидках"
                    ),
                ),
                (
                    "is_promo_email_notifications_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Email уведомления о скидках"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки пользователя",
                "verbose_name_plural": "Настройки пользователей",
            },
        ),
    ]
