# Generated by Django 6.0.1 on 2026-02-09 13:17

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_useraddress"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneVerificationCode",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Удалено"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_index=True,
                        max_length=128,
                        region="RU",
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=6, verbose_name="Код подтверждения"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(verbose_name="Время истечения кода"),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество попыток проверки"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Код использован"),
                ),
            ],
            options={
                "verbose_name": "Код подтверждения телефона",
                "verbose_name_plural": "Коды подтверждения телефона",
                "indexes": [
                    models.Index(
                        fields=["phone", "is_used", "expires_at"],
                        name="accounts_ph_phone_a384d4_idx",
                    )
                ],
            },
        ),
    ]
