# Generated by Django 6.0.3 on 2026-03-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_phoneverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='language',
            field=models.CharField(default='ru', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(default='light', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
