# Generated by Django 6.0.3 on 2026-03-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usersettings_extra_usersettings_language_and_more'),
        ('accounts', '0006_user_roles'),
    ]

    operations = [
    ]
