# Generated by Django 6.0.1 on 2026-03-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20260311_1727'),
        ('accounts', '0007_merge_20260311_2019'),
    ]

    operations = [
    ]
