# Generated by Django 6.0.1 on 2026-03-14 19:06

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_alter_promocode_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Номер чека')),
                ('fiscal_data', models.JSONField(help_text='Данные чека по 54-ФЗ', verbose_name='Фискальные данные')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлен'), ('confirmed', 'Подтверждён'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('ofd_response', models.JSONField(blank=True, null=True, verbose_name='Последний ответ ОФД')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен в')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждён в')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
        migrations.CreateModel(
            name='OFDResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField(verbose_name='Данные ответа')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP статус код')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofd_responses', to='fiscal.receipt', verbose_name='Чек')),
            ],
            options={
                'verbose_name': 'Ответ ОФД',
                'verbose_name_plural': 'Ответы ОФД',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Название товара на момент продажи', max_length=255, verbose_name='Наименование товара')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого по позиции')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Ставка НДС, %')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма НДС')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fiscal.receipt', verbose_name='Чек')),
            ],
            options={
                'verbose_name': 'Позиция чека',
                'verbose_name_plural': 'Позиции чека',
            },
        ),
        migrations.CreateModel(
            name='ReceiptStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлен'), ('confirmed', 'Подтверждён'), ('failed', 'Ошибка')], max_length=20, verbose_name='Статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='fiscal.receipt', verbose_name='Чек')),
            ],
            options={
                'verbose_name': 'История статуса чека',
                'verbose_name_plural': 'История статусов чеков',
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status', 'sent_at'], name='fiscal_rece_status_3aed7a_idx'),
        ),
    ]
