# Generated by Django 6.0.1 on 2026-03-16 03:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Номер чека')),
                ('fiscal_data', models.JSONField(verbose_name='Фискальные данные (54-ФЗ)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлен'), ('confirmed', 'Подтверждён'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('ofd_response', models.JSONField(blank=True, null=True, verbose_name='Последний ответ ОФД')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен в')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждён в')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('original_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_receipts', to='fiscal.receipt', verbose_name='Исходный чек продажи')),
                ('return_obj', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='returns.return', verbose_name='Возврат')),
            ],
            options={
                'verbose_name': 'Чек возврата',
                'verbose_name_plural': 'Чеки возвратов',
            },
        ),
        migrations.CreateModel(
            name='ReturnReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Ставка НДС, %')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма НДС')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fiscal.returnreceipt', verbose_name='Чек возврата')),
            ],
            options={
                'verbose_name': 'Позиция чека возврата',
                'verbose_name_plural': 'Позиции чека возврата',
            },
        ),
        migrations.AddIndex(
            model_name='returnreceipt',
            index=models.Index(fields=['status', 'sent_at'], name='fiscal_retu_status_41eb46_idx'),
        ),
    ]
