# Generated by Django 6.0.1 on 2026-01-26 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Удалено"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "code",
                    models.SlugField(
                        editable=False, max_length=255, unique=True, verbose_name="Код"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "delivery_radius_km",
                    models.FloatField(
                        default=3.0,
                        help_text="Указывается в километрах",
                        verbose_name="Радиус доставки",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="common.address",
                        verbose_name="Адрес",
                    ),
                ),
            ],
            options={
                "verbose_name": "Точка продаж",
                "verbose_name_plural": "Точки продаж",
            },
        ),
        migrations.CreateModel(
            name="StoreSpecialHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("open_time", models.TimeField(verbose_name="Время открытия")),
                ("close_time", models.TimeField(verbose_name="Время закрытия")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_hours",
                        to="stores.store",
                        verbose_name="Точка продаж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Специальные часы точки продаж",
                "verbose_name_plural": "Специальные часы точек продаж",
                "ordering": ("date",),
            },
        ),
        migrations.CreateModel(
            name="StoreWorkingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                ("open_time", models.TimeField(verbose_name="Время открытия")),
                ("close_time", models.TimeField(verbose_name="Время закрытия")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="stores.store",
                        verbose_name="Точка продаж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рабочие часы точки продаж",
                "verbose_name_plural": "Рабочие часы точек продаж",
                "ordering": ("day_of_week",),
            },
        ),
    ]
