# Generated by Django 6.0.1 on 2026-02-02 05:03

import autoslug.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="code",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                max_length=255,
                populate_from="name",
                unique=True,
                verbose_name="Код",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="delivery_radius_km",
            field=models.FloatField(
                default=3.0,
                help_text="Указывается в километрах",
                validators=[
                    django.core.validators.MinValueValidator(
                        0.01, message="Радиус доставки должен быть больше 0"
                    )
                ],
                verbose_name="Радиус доставки",
            ),
        ),
        migrations.AddConstraint(
            model_name="storespecialhours",
            constraint=models.UniqueConstraint(
                fields=("store", "date"), name="uniq_store_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="storeworkinghours",
            constraint=models.UniqueConstraint(
                fields=("store", "day_of_week"), name="uniq_store_day_of_week"
            ),
        ),
    ]
