# Generated by Django 6.0.3 on 2026-03-06 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_code_alter_store_delivery_radius_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_header', models.TextField(blank=True, default='', verbose_name='Заголовок чека')),
                ('receipt_footer', models.TextField(blank=True, default='', verbose_name='Подвал чека')),
                ('allow_cash', models.BooleanField(default=True, verbose_name='Разрешить наличные')),
                ('allow_card', models.BooleanField(default=True, verbose_name='Разрешить карту')),
                ('max_idle_seconds', models.PositiveIntegerField(default=120, verbose_name='Таймаут бездействия (сек)')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='stores.store', verbose_name='Точка продаж')),
            ],
            options={
                'verbose_name': 'Настройки точки продаж',
                'verbose_name_plural': 'Настройки точек продаж',
            },
        ),
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiosk_number', models.CharField(max_length=50, verbose_name='Номер кассы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosks', to='stores.store', verbose_name='Точка продаж')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
                'constraints': [models.UniqueConstraint(fields=('store', 'kiosk_number'), name='uniq_store_kiosk_number')],
            },
        ),
    ]
