# Generated by Django 6.0.1 on 2026-03-06 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_alter_store_code_alter_store_delivery_radius_km_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kiosk",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Удалено"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        unique=True,
                        verbose_name="Серийный номер",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активна"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kiosks",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Касса",
                "verbose_name_plural": "Кассы",
            },
        ),
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, verbose_name="Ключ")),
                ("value", models.TextField(verbose_name="Значение")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "Строка"),
                            ("number", "Число"),
                            ("boolean", "Булево"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=10,
                        verbose_name="Тип значения",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_settings",
                        to="stores.store",
                        verbose_name="Точка продаж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка точки продаж",
                "verbose_name_plural": "Настройки точки продаж",
            },
        ),
        migrations.AddIndex(
            model_name="kiosk",
            index=models.Index(fields=["store", "is_active"], name="stores_kios_store_i_idx"),
        ),
        migrations.AddConstraint(
            model_name="storesettings",
            constraint=models.UniqueConstraint(
                fields=["store", "key"], name="uniq_store_key"
            ),
        ),
    ]
