# Generated by Django 6.0.3 on 2026-03-11 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_storesettings_kiosk'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Координата магазина (широта)', max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='store',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Координата магазина (долгота)', max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название зоны')),
                ('radius_km', models.DecimalField(blank=True, decimal_places=2, help_text='Максимальное расстояние от магазина для данной зоны', max_digits=6, null=True, verbose_name='Радиус зоны (км)')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальная сумма заказа')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('delivery_time_minutes', models.IntegerField(help_text='ETA в минутах', verbose_name='Время доставки (минут)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Зона доставки',
                'verbose_name_plural': 'Зоны доставки',
                'ordering': ('radius_km',),
                'indexes': [models.Index(fields=['store', 'is_active'], name='stores_deli_store_i_dee976_idx')],
            },
        ),
    ]
