# Generated by Django 6.0.3 on 2026-03-11 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_address_comment'),
        ('orders', '0001_initial'),
        ('stores', '0003_storesettings_kiosk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='common.address', verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает'), ('assigned', 'Курьер назначен'), ('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('failed', 'Не удалось доставить')], max_length=20, null=True, verbose_name='Статус доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ожидаемое время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз'), ('kiosk', 'Касса')], default='delivery', max_length=10, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Ожидает обработки'), ('pending_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Ожидает обработки'), ('pending_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'status'], name='orders_orde_order_t_1378c7_idx'),
        ),
    ]
