# Generated by Django 6.0.3 on 2026-03-11 12:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_fields'),
        ('products', '0005_stock_reserved_quantity_alter_stock_quantity'),
        ('stores', '0004_delivery_zone_store_coords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает в')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Выполнен'), ('expired', 'Истёк'), ('released', 'Освобождён')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Освобождён в')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='products.product', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Резервирование',
                'verbose_name_plural': 'Резервирования',
                'indexes': [models.Index(fields=['product', 'store'], name='orders_rese_product_5c1b52_idx'), models.Index(fields=['status', 'expires_at'], name='orders_rese_status_980671_idx')],
            },
        ),
    ]
