# Generated by Django 6.0.1 on 2026-03-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_promo_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
    ]
