# Generated by Django 6.0.1 on 2026-02-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("parent__sort_order", "sort_order", "name"),
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
