# Generated by Django 6.0.3 on 2026-03-07 06:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_barcode'),
        ('stores', '0003_storesettings_kiosk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Цена не может быть отрицательной.')], verbose_name='Цена')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('effective_from', models.DateField(verbose_name='Дата начала действия')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Дата окончания действия')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Цена товара',
                'verbose_name_plural': 'Цены товаров',
                'ordering': ('-effective_from',),
            },
        ),
        migrations.RenameIndex(
            model_name='barcode',
            new_name='products_ba_code_f2685f_idx',
            old_name='products_ba_code_idx',
        ),
        migrations.RenameIndex(
            model_name='barcode',
            new_name='products_ba_product_b838ab_idx',
            old_name='products_ba_product_idx',
        ),
        migrations.RenameIndex(
            model_name='barcode',
            new_name='products_ba_barcode_1b795b_idx',
            old_name='products_ba_barcode_idx',
        ),
        migrations.RenameIndex(
            model_name='barcode',
            new_name='products_ba_product_fa7e62_idx',
            old_name='products_ba_product_primary_idx',
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stores.store', verbose_name='Точка продаж'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(fields=('product', 'store', 'effective_from'), name='uniq_product_store_effective_from'),
        ),
    ]
