# Generated by Django 6.0.3 on 2026-03-09 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price'),
        ('stores', '0003_storesettings_kiosk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Код маркировки (Data Matrix)')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('sold', 'Продана'), ('returned', 'Возвращена'), ('withdrawn', 'Выведена из оборота')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('marked_at', models.DateTimeField(verbose_name='Дата маркировки')),
                ('event_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего события')),
                ('barcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markings', to='products.barcode', verbose_name='Штрихкод')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markings', to='products.product', verbose_name='Товар')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markings', to='stores.store', verbose_name='Точка продаж')),
            ],
            options={
                'verbose_name': 'Маркировка',
                'verbose_name_plural': 'Маркировки',
                'indexes': [models.Index(fields=['code'], name='products_ma_code_87e471_idx'), models.Index(fields=['product_id', 'status'], name='products_ma_product_71dfdf_idx'), models.Index(fields=['store_id', 'status'], name='products_ma_store_i_8147f0_idx')],
            },
        ),
    ]
